### ISSUE TITLE
feature.py  KeyError: 'pseudo_bias'

### ISSUE THREAD

**Issue by 2efPer** [Urinx/alphafold_pytorch#32]
```
error: save: error compressing data element
error: called from
    plmDCA at line 165 column 5

/Users/mac/lab/guo/alphafold_pytorch
Traceback (most recent call last):
  File "feature.py", line 263, in <module>
    feature_generation(SEQ_FILE, OUT_FILE)
  File "feature.py", line 168, in feature_generation
    pseudo_bias = np.float32(mat['pseudo_bias'])
KeyError: 'pseudo_bias'
``` 
 Can anyone help?

**Comment by 2efPer** [comment]
My girlfriend broke up with me, so i don't need to use this anymore and don't wanna see it ,so I will close this issue.
