### ISSUE TITLE
TypeError: pad() missing 1 required positional argument: 'mode'

### ISSUE THREAD

**Issue by sean-lin-tw** [Urinx/alphafold_pytorch#9]
Hi,
I am trying to run the PyTorch AlphaFold implementation on my server with Python 3.6.8, PyTorch 1.5.0, and TensorFlow 2.0.0-alpha0. But it cannot be successfully executed.
Here is the error message.
```
Device: cuda
Model parameters: 21182345
Load tf model cost time: 0:00:33.470121
Data:  T1019s2-l64_s24 64
Traceback (most recent call last):
  File "alphafold.py", line 223, in <module>
    run_eval(TARGET_PATH, MODEL_PATH, REPLICA, OUT_DIR, DEVICE)
  File "alphafold.py", line 54, in run_eval
    for x_2d, crop_x, crop_y in crops:
  File "dataset.py", line 317, in make_crops
    [0, 0]]
TypeError: pad() missing 1 required positional argument: 'mode'
Input file: test_data/T1019s2.pkl
Output dir: T1019s2_out/Torsion/0
Torsion model: model/941521
Replica: 0
```

**Comment by sean-lin-tw** [comment]
I found that it is a issue of numpy 1.16. 
I updated numpy and it can run (with T1019s2.pkl as input).
